### ISSUE TITLE
master分支clone下来跑不起来

### ISSUE THREAD

**Issue by xiaosazixian** [stbui/angular-material-app#13]
master分支clone下来跑不起来，提示缺少依赖包，然后安装缺少的依赖挨个加，最后还是报错
```
`ERROR in ./src/styles.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\vendor'
    at Object.fs.readdirSync (fs.js:862:18)
    at Object.getInstalledBinaries (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\extensions.js:128:13)
    at foundBinariesList (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\errors.js:45:5)
    at module.exports (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\example\angular-material-app\node_modules\_sass-loader@6.0.6@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:573:32)
 @ multi ./src/styles.scss
ERROR in ./src/styles.scss
Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\vendor'
    at Object.fs.readdirSync (fs.js:862:18)
    at Object.getInstalledBinaries (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\extensions.js:128:13)
    at foundBinariesList (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\errors.js:45:5)
    at module.exports (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\example\angular-material-app\node_modules\_node-sass@4.7.2@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\example\angular-material-app\node_modules\_sass-loader@6.0.6@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:573:32)
    at runLoaders (E:\example\angular-material-app\node_modules\_webpack@3.10.0@webpack\lib\NormalModule.js:195:19)
    at E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:364:11
    at E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:165:10)
    at E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:165:10)
    at E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (E:\example\angular-material-app\node_modules\_loader-runner@2.3.0@loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (E:\example\angular-material-app\node_modules\_webpack@3.10.0@webpack\lib\NormalModule.js:182:3)
    at NormalModule.build (E:\example\angular-material-app\node_modules\_webpack@3.10.0@webpack\lib\NormalModule.js:275:15)
 @ ./src/styles.scss
 @ multi ./src/styles.scss
ERROR in multi ./node_modules/normalize.css/normalize.css ./node_modules/material-design-icons/iconfont/material-icons.css ./node_modules/quill/dist/quill.snow.css
Module not found: Error: Can't resolve 'E:\example\angular-material-app\node_modules\quill\dist\quill.snow.css' in 'E:\example\angular-material-app\node_modules\_@angular_cli@1.6.3@@angular\cli\models\webpack-configs'
resolve 'E:\example\angular-material-app\node_modules\quill\dist\quill.snow.css' in 'E:\example\angular-material-app\node_modules\_@angular_cli@1.6.3@@angular\cli\models\webpack-configs'
  using description file: E:\example\angular-material-app\node_modules\_@angular_cli@1.6.3@@angular\cli\package.json (relative path: ./models/webpack-configs)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: E:\example\angular-material-app\node_modules\_@angular_cli@1.6.3@@angular\cli\package.json (relative path: ./models/webpack-configs)
    using description file: E:\example\angular-material-app\package.json (relative path: ./node_modules/quill/dist/quill.snow.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        E:\example\angular-material-app\node_modules\quill\dist\quill.snow.css doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        E:\example\angular-material-app\node_modules\quill\dist\quill.snow.css.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        E:\example\angular-material-app\node_modules\quill\dist\quill.snow.css.js doesn't exist
      as directory
        E:\example\angular-material-app\node_modules\quill\dist\quill.snow.css doesn't exist
`
```

**Comment by stbui** [comment]
明显是scss编译不成功

**Comment by xiaosazixian** [comment]
@stbui 这个包安装后，后续还会有一系列需要安装的缺失依赖，我挨个装好后还是不行，所以就把package.json还原了在把报错信息贴上来的。

**Comment by stbui** [comment]
贴报错日志

**Comment by xiaosazixian** [comment]
没事，可能是我自己的问题，我再看看
