### ISSUE TITLE
Error build grpc on npm install

### ISSUE THREAD

**Issue by yongzhangf** [stbui/angular-material-app#17]
```
npm install 时出现编译错误，怎么解决呢？
环境：Windows 10, Node 8.9.0, Npm: 5.5.1
```

  
Error logs:
```
 ............ 
  gzwrite.c
  infback.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  uncompr.c
  zutil.c
  win_delay_load_hook.cc
  z.vcxproj -> D:\work\50_Research\angular-material-app\node_modules\grpc\build\Release\\libz.lib
gyp ERR! build error
gyp ERR! stack Error: `D:\Development\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\work\50_Research\angular-material-app\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\Development\\nodejs\\node.exe" "D:\\work\\50_Research\\angular-material-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=D:\\work\\50_Research\\angular-material-app\\node_modules\\grpc\\src\\node\\extension_binary\\node-v57-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=D:\\work\\50_Research\\angular-material-app\\node_modules\\grpc\\src\\node\\extension_binary\\node-v57-win32-x64-unknown"
gyp ERR! cwd D:\work\50_Research\angular-material-app\node_modules\grpc
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Development\nodejs\node.exe D:\work\50_Research\angular-material-app\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=D:\work\50_Research\angular-material-app\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\work\50_Research\angular-material-app\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\work\50_Research\angular-material-app\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "D:\\Development\\nodejs\\node.exe" "D:\\work\\50_Research\\angular-material-app\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd D:\work\50_Research\angular-material-app\node_modules\grpc
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'D:\Development\nodejs\node.exe D:\work\50_Research\angular-material-app\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=D:\work\50_Research\angular-material-app\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\work\50_Research\angular-material-app\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown' (1)
npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-simple-ast@0.97.1 requires a peer of typescript@2.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
Waiting for installers... /
npm ERR! grpc@1.7.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by yongzhangf** [comment]
node-gpy是安装成功的。
但是Windows下，node-gpy编译grpc是出错误的。

gprc的issues也没有找到解决方法。https://github.com/grpc/grpc/issues/13657

暂时在Ubuntu下构建项目了。
