### ISSUE TITLE
Cannot find module 'babel-runtime/helpers/taggedTemplateLiteral'

### ISSUE THREAD

**Issue by smile2014** [stbui/angular-material-app#5]
Error: Cannot find module 'babel-runtime/helpers/taggedTemplateLiteral'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\angular-material-app\node_modules\.1.4.0@common-tags\lib\TemplateTag\TemplateTag.js:12:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by stbui** [comment]
问题是怎么出现的，详细描述操作步骤和使用环境
